name: flutter_radar_view
description: A customizable and interactive radar view widget for Flutter that allows you to display and interact with multiple spots on a radar.
version: 0.0.8
homepage: https://github.com/OtavioHo/flutter_radar_view

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  touchable: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
